SKILLS = [
    # Programming Languages
    'python',
    'java',
    'c++',
    'c',
    'javascript',
    'typescript',
    'r',
    'go',
    'kotlin',
    'swift',
    'php',
    'ruby',
    'scala',
    'matlab',
    'rust',
    'perl',
    'groovy',
    'haskell',
    'elixir',
    'clojure',
    'c#',
    'vb.net',
    
    # Web Technologies
    'html',
    'css',
    'react',
    'angular',
    'vue',
    'node.js',
    'nodejs',
    'django',
    'flask',
    'fastapi',
    'rest api',
    'graphql',
    'bootstrap',
    'tailwind',
    'webpack',
    'babel',
    'nextjs',
    'next.js',
    'nuxt',
    'express',
    'asp.net',
    'spring boot',
    'jquery',
    'sass',
    'less',
    'web development',
    
    # Data Science & Machine Learning
    'machine learning',
    'deep learning',
    'nlp',
    'natural language processing',
    'computer vision',
    'tensorflow',
    'pytorch',
    'keras',
    'scikit-learn',
    'sklearn',
    'pandas',
    'numpy',
    'matplotlib',
    'seaborn',
    'opencv',
    'nltk',
    'spacy',
    'hugging face',
    'llm',
    'generative ai',
    'gen ai',
    'reinforcement learning',
    'neural networks',
    'cnn',
    'rnn',
    'lstm',
    'gru',
    'xgboost',
    'gradient boosting',
    'random forest',
    'decision trees',
    'svm',
    'data mining',
    'feature engineering',
    'bayesian',
    'statistical analysis',
    'a/b testing',
    'ab testing',
    'ml',
    'ai',
    'artificial intelligence',
    
    # Databases & Data Platforms
    'sql',
    'mysql',
    'postgresql',
    'postgres',
    'mongodb',
    'mongo',
    'sqlite',
    'firebase',
    'redis',
    'oracle',
    'power bi',
    'powerbi',
    'tableau',
    'excel',
    'data analysis',
    'data visualization',
    'etl',
    'hadoop',
    'spark',
    'kafka',
    'cassandra',
    'dynamodb',
    'elasticsearch',
    'elastic search',
    'neo4j',
    'hive',
    'pig',
    'sqoop',
    'flume',
    'data warehouse',
    'snowflake',
    'bigquery',
    'redshift',
    'nosql',
    'relational database',
    
    # DevOps & Cloud
    'git',
    'github',
    'gitlab',
    'docker',
    'kubernetes',
    'k8s',
    'aws',
    'amazon web services',
    'azure',
    'gcp',
    'google cloud',
    'cloud computing',
    'linux',
    'unix',
    'bash',
    'shell scripting',
    'ci/cd',
    'jenkins',
    'terraform',
    'ansible',
    'puppet',
    'chef',
    'prometheus',
    'grafana',
    'elk stack',
    'datadog',
    'newrelic',
    'cloudformation',
    'azure devops',
    'gitlab ci',
    'github actions',
    'container orchestration',
    'microservices',
    'devops',
    'infrastructure as code',
    'iac',
    
    # Security & Testing
    'cybersecurity',
    'network security',
    'encryption',
    'ssl',
    'tls',
    'oauth',
    'jwt',
    'penetration testing',
    'unit testing',
    'integration testing',
    'selenium',
    'junit',
    'pytest',
    'jest',
    'mocha',
    'cypress',
    'jira',
    'qa automation',
    'qa',
    'quality assurance',
    'security',
    'testing',
    
    # Soft Skills
    'communication',
    'leadership',
    'teamwork',
    'team work',
    'problem solving',
    'critical thinking',
    'time management',
    'project management',
    'agile',
    'scrum',
    'kanban',
    'stakeholder management',
    'presentation',
    'negotiation',
    'mentoring',
    'conflict resolution',
    'adaptability',
    'collaboration',
    'interpersonal skills',
]
